# Generated by Django 4.0.3 on 2022-04-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_trivia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='incorrect_answer1',
            new_name='incorrect_answer_one',
        ),
        migrations.RenameField(
            model_name='trivia',
            old_name='incorrect_answer2',
            new_name='incorrect_answer_three',
        ),
        migrations.RenameField(
            model_name='trivia',
            old_name='incorrect_answer3',
            new_name='incorrect_answer_two',
        ),
    ]
